# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number1', models.CharField(max_length=10)),
                ('Number2', models.CharField(max_length=10)),
                ('Result', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='integrations',
            name='number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Numbers'),
        ),
    ]
