# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubjectName', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TeacherName', models.CharField(max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='integrations',
            name='number',
        ),
        migrations.DeleteModel(
            name='Integrations',
        ),
        migrations.DeleteModel(
            name='Numbers',
        ),
        migrations.AddField(
            model_name='subjects',
            name='Subjects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Teachers'),
        ),
    ]
