# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-03 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161103_0906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjects',
            old_name='SubjectName',
            new_name='Subject_Name',
        ),
        migrations.RenameField(
            model_name='subjects',
            old_name='Subjects',
            new_name='Teacher',
        ),
    ]
